server:
  port: 8080
  servlet:
    context-path: /demo-service
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/employees
    username: postgres
    password: 12345
  liquibase:
    enabled: 'true'
    drop-first: 'false'
    change-log: classpath:db/changelog/changelog-master.xml
    parameters:
      liquibase.changelogLockWaitTimeInMinutes: 20
  jpa:
    hibernate:
      ddl-auto: none